"""What the exported map says about itself.

The three classes -- provided by you, generated by BT5, noted by BT5 -- are the
whole point, so the tests check that a reader can tell them apart from the file
alone, and that BT5 never states something it cannot support.
"""

from __future__ import annotations

import io
from dataclasses import replace

from bt5.core.types import Interval
from bt5.vector import (
    ORIGIN_QUALIFIER,
    DesignNote,
    VectorBackbone,
    annotate,
    assemble,
    backbone_to_record,
    construct_to_record,
    read_genbank,
    write_genbank,
)
from bt5.vector.annotate import COMMENT_WIDTH
from conftest import make_cds

BANNED = ("predict", "will express", "fold-improvement", "titer of", "yield of")


def annotated(backbone: VectorBackbone, n_codons: int = 150, **kw: object):  # type: ignore[no-untyped-def]
    cds, protein = make_cds(n_codons)
    assembly = assemble(backbone, cds, protein=protein, table_id=1)
    return annotate(assembly, source_name=backbone.name, **kw)  # type: ignore[arg-type]


class TestFeatureOrigin:
    def test_every_feature_says_which_side_it_came_from(self, backbone: VectorBackbone) -> None:
        construct, _ = annotated(backbone)
        origins = {f.qualifiers[ORIGIN_QUALIFIER][0] for f in construct.features}
        assert origins <= {"provided", "designed", "noted"}
        assert "provided" in origins
        assert "designed" in origins

    def test_only_the_cds_is_marked_designed(self, backbone: VectorBackbone) -> None:
        construct, _ = annotated(backbone)
        designed = [
            f for f in construct.features if f.qualifiers[ORIGIN_QUALIFIER] == ("designed",)
        ]
        assert len(designed) == 1
        assert designed[0].kind == "CDS"

    def test_marking_does_not_disturb_the_users_own_qualifiers(
        self, backbone: VectorBackbone
    ) -> None:
        construct, _ = annotated(backbone)
        wpre = next(f for f in construct.features if f.qualifiers.get("label") == ("WPRE",))
        assert (
            wpre.qualifiers["note"]
            == next(
                f for f in backbone.features if f.qualifiers.get("label") == ("WPRE",)
            ).qualifiers["note"]
        )


class TestNotedFindings:
    def test_identical_ltrs_are_reported_with_a_protocol(self, backbone: VectorBackbone) -> None:
        """The backbone is never edited, so a located warning is the whole answer."""
        _, report = annotated(backbone)
        repeat = next(n for n in report.notes if n.kind == "liability" and "identical" in n.summary)
        assert repeat.bears_on == "plasmid stability"
        assert "recA-" in repeat.action
        assert "250 bp" in repeat.summary

    def test_an_upstream_atg_in_the_users_utr_is_reported(self, backbone: VectorBackbone) -> None:
        _, report = annotated(backbone)
        uaug = [n for n in report.notes if "upstream ATG" in n.summary]
        assert uaug, "an ATG in the 5'UTR is real, unfixable by codon choice, and must be said"
        assert all(n.bears_on == "protein expression" for n in uaug)
        assert all("no codon choice can remove it" in n.action for n in uaug)

    def test_an_upstream_atg_note_points_at_an_actual_atg(self, backbone: VectorBackbone) -> None:
        construct, report = annotated(backbone)
        for note in report.notes:
            if "upstream ATG" in note.summary:
                assert note.interval is not None
                assert construct.slice(note.interval) == "ATG"

    def test_no_uaug_note_when_there_is_no_utr(self, backbone: VectorBackbone) -> None:
        stripped = replace(
            backbone,
            features=tuple(f for f in backbone.features if f.kind not in ("5'UTR", "promoter")),
        )
        _, report = annotated(stripped)
        assert not any("upstream ATG" in n.summary for n in report.notes)
        assert any(n.kind == "unavailable" for n in report.notes)

    def test_located_notes_become_features_on_the_map(self, backbone: VectorBackbone) -> None:
        construct, report = annotated(backbone)
        located = [n for n in report.notes if n.interval is not None]
        marks = [f for f in construct.features if f.qualifiers.get(ORIGIN_QUALIFIER) == ("noted",)]
        assert len(marks) == len(located)
        assert all(f.kind == "misc_feature" for f in marks)

    def test_an_unlocated_note_does_not_invent_an_interval(self, backbone: VectorBackbone) -> None:
        """Putting a warning on sequence it does not describe is worse than the COMMENT."""
        construct, report = annotated(backbone)
        unlocated = [n for n in report.notes if n.interval is None]
        assert unlocated
        for note in unlocated:
            assert note.summary not in "".join(
                f.qualifiers.get("note", ("",))[0]
                for f in construct.features
                if f.qualifiers.get(ORIGIN_QUALIFIER) == ("noted",)
            )

    def test_a_rule_can_contribute_a_finding(self, backbone: VectorBackbone) -> None:
        """The seam the rules lane plugs into, without this module knowing rules."""
        extra = DesignNote(
            kind="liability",
            summary="cryptic splice donor in the backbone",
            interval=Interval(400, 409),
            bears_on="protein expression",
        )
        construct, report = annotated(backbone, extra_notes=(extra,))
        assert extra in report.notes
        assert any(
            f.qualifiers.get("note", ("",))[0].startswith("[liability]")
            and f.interval == Interval(400, 409)
            for f in construct.features
        )


class TestComment:
    def test_the_three_sections_are_present(self, backbone: VectorBackbone) -> None:
        _, report = annotated(backbone)
        comment = report.to_comment()
        assert "== PROVIDED BY YOU ==" in comment
        assert "== GENERATED BY BT5 ==" in comment
        assert "== NOTED BY BT5 ==" in comment

    def test_it_states_what_you_gave_and_what_bt5_made(self, backbone: VectorBackbone) -> None:
        _, report = annotated(backbone)
        comment = report.to_comment()
        assert "pBT5_SYNTH_LENTI, 2000 bp, circular" in comment
        assert "861..1310, 150 codons" in comment
        assert "NCBI translation table 1" in comment

    def test_it_makes_no_expression_claim(self, backbone: VectorBackbone) -> None:
        """The product stance, enforced where a user would actually read it."""
        _, report = annotated(backbone)
        # Wrapping at COMMENT_WIDTH puts newlines mid-sentence, so search the
        # unwrapped text -- that is what a reader sees, and what a grep for
        # prediction vocabulary has to work against.
        comment = " ".join(report.to_comment().split()).lower()
        assert "never a predicted expression level, titer or yield" in comment
        for phrase in BANNED:
            assert comment.count(phrase) <= (1 if phrase == "predict" else 0), phrase

    def test_no_line_exceeds_the_width_biopython_will_rewrap(
        self, backbone: VectorBackbone
    ) -> None:
        """69+ chars is re-wrapped on write and re-read as a new line, breaking
        idempotence -- and Biopython warns, which this repo treats as an error."""
        _, report = annotated(backbone)
        assert max(len(line) for line in report.to_comment().splitlines()) <= COMMENT_WIDTH

    def test_the_design_hash_appears_when_given(self, backbone: VectorBackbone) -> None:
        _, report = annotated(backbone, design_hash="deadbeef")
        assert "design: deadbeef" in report.to_comment()

    def test_no_hash_line_when_none_is_supplied(self, backbone: VectorBackbone) -> None:
        _, report = annotated(backbone)
        assert "design:" not in report.to_comment()


class TestExport:
    def test_the_report_survives_a_round_trip(self, backbone: VectorBackbone) -> None:
        construct, report = annotated(backbone)
        text = write_genbank(construct_to_record(construct, name="designed"))
        again = read_genbank(io.StringIO(text))
        assert again.annotations["comment"] == report.to_comment()

    def test_the_annotated_export_is_still_idempotent(self, backbone: VectorBackbone) -> None:
        construct, _ = annotated(backbone)
        first = write_genbank(construct_to_record(construct, name="designed"))
        second = write_genbank(backbone_to_record(read_genbank(io.StringIO(first))))
        assert first == second

    def test_the_origin_qualifier_survives_export(self, backbone: VectorBackbone) -> None:
        construct, _ = annotated(backbone)
        text = write_genbank(construct_to_record(construct, name="designed"))
        assert '/bt5_origin="designed"' in text
        assert '/bt5_origin="provided"' in text
