"""What the exported map says about itself.

Three classes of information, kept visibly separate, because six months later the
only question that matters about a plasmid map is "which of this did I draw and
which did the software?":

  PROVIDED BY YOU     every base and every feature that came from the input
                      vector, carried through unchanged and proved byte-identical
  GENERATED BY BT5    the designed CDS and the feature describing it
  NOTED BY BT5        observations about sequence BT5 did NOT write -- backbone
                      liabilities, assumptions it had to make, objectives it
                      could not evaluate, and edits it made to the map itself

The third class is the one with no equivalent in other tools. BT5 never edits the
backbone, so when the backbone is the problem the only honest output is a located
warning and a protocol suggestion. A user who has been told their two LTRs are a
250 bp perfect repeat can pick the right strain; one who has not, cannot.

Nothing here predicts an expression level, titer, yield or fold-improvement. The
notes say what is present and what BT5 could not do.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, replace
from textwrap import wrap

from bt5.core.types import Construct, Feature, Interval, SegmentKind
from bt5.vector.assemble import Assembly
from bt5.vector.kmers import ConstructKmerIndex, RepeatPair
from bt5.vector.notes import DesignNote, format_span

#: Biopython re-wraps a COMMENT line longer than this, which turns one logical
#: line into two on the next read and makes the writer non-idempotent -- and it
#: warns while doing it, which this repo promotes to a test failure. Measured,
#: not guessed: 68 is stable and 69 is not.
COMMENT_WIDTH = 68

#: Qualifier marking which side of the boundary a feature came from. A distinct
#: key rather than an extra /note so it is greppable and cannot be confused with
#: annotation the user wrote.
ORIGIN_QUALIFIER = "bt5_origin"

_DISCLAIMER = (
    "BT5 reports ranks and percentiles, never a predicted expression level, titer or yield."
)


@dataclass(frozen=True)
class DesignReport:
    """The three-class summary, renderable to a GenBank COMMENT or a QC report."""

    source_name: str
    source_length: int
    topology: str
    backbone_bases: int
    features_kept: int
    cds_span: str
    codons: int
    protein_length: int
    table_id: int
    utr_source: str
    utr_span: str
    notes: tuple[DesignNote, ...]
    construct_length: int
    design_hash: str | None = None

    def provided_lines(self) -> tuple[str, ...]:
        return (
            f"vector: {self.source_name}, {self.source_length} bp, {self.topology}",
            f"backbone kept: {self.backbone_bases} bp, verified byte-identical",
            f"features kept: {self.features_kept}",
            f"5' UTR: {self.utr_span} ({self.utr_source})",
        )

    def generated_lines(self) -> tuple[str, ...]:
        lines = [
            f"CDS: {self.cds_span}, {self.codons} codons, {self.protein_length} aa",
            f"genetic code: NCBI translation table {self.table_id}",
        ]
        if self.design_hash:
            lines.append(f"design: {self.design_hash}")
        return tuple(lines)

    def note_lines(self) -> tuple[str, ...]:
        return tuple(note.render(self.construct_length) for note in self.notes)

    def to_comment(self) -> str:
        """Render as a GenBank COMMENT body.

        Flat by necessity: Biopython's reader strips leading whitespace and drops
        blank lines from a COMMENT, so indentation-based structure does not
        survive a round trip. Section markers and bullets carry it instead.
        """
        blocks: list[str] = [f"Designed by BT5. {_DISCLAIMER}"]
        blocks.append("== PROVIDED BY YOU ==")
        blocks.extend(f"- {line}" for line in self.provided_lines())
        blocks.append("== GENERATED BY BT5 ==")
        blocks.extend(f"- {line}" for line in self.generated_lines())
        note_lines = self.note_lines()
        if note_lines:
            blocks.append("== NOTED BY BT5 ==")
            blocks.extend(f"- {line}" for line in note_lines)
        else:
            blocks.append("== NOTED BY BT5 ==")
            blocks.append("- nothing further to report.")

        out: list[str] = []
        for block in blocks:
            out.extend(wrap(block, width=COMMENT_WIDTH) or [""])
        return "\n".join(out)


def annotate(
    assembly: Assembly,
    *,
    source_name: str,
    design_hash: str | None = None,
    extra_notes: Sequence[DesignNote] = (),
) -> tuple[Construct, DesignReport]:
    """Return the construct with its provenance annotation, plus the report.

    `extra_notes` is the seam for the rules lane: a rule that finds something in
    the backbone it cannot fix hands it over as a `DesignNote` and it lands on
    the map, without this module knowing anything about rules.
    """
    construct = assembly.construct
    findings = (
        *assembly.notes,
        *_identical_exempt_repeats(construct),
        *_repeat_liabilities(construct),
        *_upstream_start_codons(construct, assembly),
        *extra_notes,
    )
    report = _build_report(assembly, source_name, design_hash, findings)
    annotated = replace(
        construct,
        features=(*_marked(construct, assembly), *_note_features(findings, construct.length)),
        annotations={**construct.annotations, "comment": report.to_comment()},
    )
    return annotated, report


def _build_report(
    assembly: Assembly,
    source_name: str,
    design_hash: str | None,
    findings: Sequence[DesignNote],
) -> DesignReport:
    construct = assembly.construct
    cds = assembly.cds_interval
    unit = construct.translation_units[0]
    backbone_bases = construct.length - cds.length
    utr = assembly.utr.five_prime
    return DesignReport(
        source_name=source_name,
        source_length=assembly.remapper.old_length,
        topology=construct.topology.value,
        backbone_bases=backbone_bases,
        features_kept=sum(1 for f in construct.features if f.uid != "cds"),
        cds_span=format_span(cds, construct.length),
        codons=cds.length // 3,
        protein_length=len(unit.protein),
        table_id=unit.table_id,
        utr_source=assembly.utr.five_prime_source.replace("_", " "),
        utr_span=format_span(utr, construct.length) if utr else "not found",
        notes=tuple(findings),
        construct_length=construct.length,
        design_hash=design_hash,
    )


def _marked(construct: Construct, assembly: Assembly) -> tuple[Feature, ...]:
    """Tag every feature with which side of the CDS/backbone boundary it came from."""
    out: list[Feature] = []
    for feature in construct.features:
        origin = "designed" if feature.uid == "cds" else "provided"
        out.append(
            replace(
                feature,
                qualifiers={**feature.qualifiers, ORIGIN_QUALIFIER: (origin,)},
            )
        )
    return tuple(out)


def _note_features(notes: Sequence[DesignNote], length: int) -> tuple[Feature, ...]:
    """Put located notes on the map, so they are visible in a sequence viewer.

    An unlocated note reaches the user through the COMMENT only; inventing an
    interval for it would put a warning on sequence it does not describe.
    """
    out: list[Feature] = []
    for index, note in enumerate(n for n in notes if n.interval is not None):
        assert note.interval is not None
        out.append(
            Feature(
                interval=note.interval,
                kind="misc_feature",
                qualifiers={
                    "label": (f"BT5 {note.kind}",),
                    "note": (note.render(length),),
                    ORIGIN_QUALIFIER: ("noted",),
                },
                uid=f"bt5note{index:03d}",
            )
        )
    return tuple(out)


# -- findings BT5 can compute today ---------------------------------------


def _identical_exempt_repeats(construct: Construct) -> tuple[DesignNote, ...]:
    """Report scan-exempt regions that are exact copies of each other.

    LTRs and ITRs are whitelisted precisely because they violate the repeat rules
    by construction, and no codon choice can change them -- so the deliverable is
    a strain and temperature protocol, not a redesign. Saying nothing would leave
    the user to discover it as a deletion after a maxiprep.
    """
    exempt = [s for s in construct.segments if s.kind is SegmentKind.WHITELISTED_REPEAT]
    out: list[DesignNote] = []
    for i, first in enumerate(exempt):
        for second in exempt[i + 1 :]:
            if construct.slice(first.interval) != construct.slice(second.interval):
                continue
            out.append(
                DesignNote(
                    kind="liability",
                    summary=(
                        f"{first.label or 'region'} and {second.label or 'region'} are "
                        f"identical over {first.interval.length} bp "
                        f"({format_span(second.interval, construct.length)})"
                    ),
                    interval=first.interval,
                    bears_on="plasmid stability",
                    action=(
                        "propagate in a recA- strain such as Stbl3 at 30 C; note that "
                        "this suppresses the RecA-dependent pathway only, which is the "
                        "one that acts on repeats this long"
                    ),
                )
            )
    return tuple(out)


def _repeat_liabilities(construct: Construct, *, min_len: int = 20) -> tuple[DesignNote, ...]:
    """Exact repeats anywhere in the assembled construct, clustered by region.

    Scoped to the whole construct on purpose: a repeat between the insert and the
    backbone is exactly as destabilising as one inside either, and it is only
    visible once they are assembled. Whitelisted ITR/LTR regions are excluded --
    they are an accepted design feature reported separately, not a finding.

    Overlapping pairs are CLUSTERED. A tandem array such as a Gal4 UAS or a TetO
    operator block yields one exact-repeat pair per offset -- fourteen of them on
    a real BiTE vector -- and fourteen near-identical notes bury the finding they
    are trying to deliver. One note per repetitive region, carrying the worst
    risk and the longest identity in it, is what a user can act on.
    """
    pairs = [
        p
        for p in ConstructKmerIndex.of(construct, min_len).repeat_pairs(
            min_len, exclude=construct.exempt
        )
        if p.risk != "low"
    ]
    out: list[DesignNote] = []
    for cluster in _cluster(pairs):
        worst = max(cluster, key=lambda p: (p.risk == "high", p.length))
        longest = max(p.length for p in cluster)
        lo = min(p.first.start for p in cluster)
        hi = max(p.first.end for p in cluster)
        tandem = any(p.tandem for p in cluster)
        if len(cluster) == 1:
            where = "in tandem" if worst.tandem else f"{worst.spacer} bp apart"
            summary = (
                f"{worst.length} bp exact repeat, {where} "
                f"(copies at {worst.first.start + 1} and {worst.second.start + 1})"
            )
        else:
            summary = (
                f"repetitive region of {hi - lo} bp containing {len(cluster)} exact "
                f"repeats up to {longest} bp" + (", some in tandem" if tandem else "")
            )
        out.append(
            DesignNote(
                kind="liability",
                summary=f"{summary}; {worst.risk} risk",
                interval=Interval(lo, hi),
                bears_on="plasmid stability and DNA synthesis",
                action=(
                    "a recA- strain such as Stbl3 suppresses this length class"
                    if worst.reca_strain_helps
                    else "a recA- strain does NOT help here: below about 200 bp, "
                    "deletion is RecA-independent"
                ),
            )
        )
    return tuple(out)


def _cluster(pairs: Sequence[RepeatPair]) -> list[list[RepeatPair]]:
    """Group pairs whose copies fall in the same stretch of sequence."""
    clusters: list[list[RepeatPair]] = []
    for pair in sorted(pairs, key=lambda p: p.first.start):
        # Cluster on the FIRST copy only. Two copies far apart are two regions;
        # spanning them would report the whole distance between them as
        # "repetitive", which on a lentiviral vector means the entire payload.
        span = pair.first
        for cluster in clusters:
            lo = min(p.first.start for p in cluster)
            hi = max(p.first.end for p in cluster)
            if span.start < hi and lo < span.end:
                cluster.append(pair)
                break
        else:
            clusters.append([pair])
    return clusters


def _upstream_start_codons(construct: Construct, assembly: Assembly) -> tuple[DesignNote, ...]:
    """Report ATGs in the user's 5'UTR.

    These are in the BACKBONE, so they are real and unfixable by codon choice --
    exactly the class of finding that has to be reported rather than solved. An
    upstream ATG either opens a short ORF that terminates before the real start,
    or runs into the CDS out of frame; both are documented causes of reduced
    protein output, and neither is visible from the CDS alone.
    """
    utr = assembly.utr.five_prime
    if utr is None:
        return ()
    text = construct.slice(utr)
    out: list[DesignNote] = []
    for offset in range(len(text) - 2):
        if text[offset : offset + 3] != "ATG":
            continue
        remaining = len(text) - offset
        in_frame_with_cds = remaining % 3 == 0
        out.append(
            DesignNote(
                kind="liability",
                summary=(
                    f"upstream ATG {offset + 1} nt into the 5'UTR, "
                    + (
                        "in frame with the start codon"
                        if in_frame_with_cds
                        else "out of frame with the start codon"
                    )
                ),
                interval=_utr_offset(utr, offset, construct.length),
                bears_on="protein expression",
                action=(
                    "this is in the backbone and no codon choice can remove it; "
                    "edit the 5'UTR in your vector if you want it gone"
                ),
            )
        )
    return tuple(out)


def _utr_offset(utr: Interval, offset: int, length: int) -> Interval:
    """Turn an offset along the UTR (5'->3') into construct coordinates."""
    if utr.strand == 1:
        start = (utr.start + offset) % length
        return Interval(start, start + 3, 1)
    end = utr.end - offset
    start = (end - 3) % length
    return Interval(start, start + 3, -1)
