"""Reading a plasmid BT5 was not asked to redesign.

Every other entry point in this lane assumes there is a protein to back-translate.
Plenty of useful plasmids have none -- an sgRNA under a U6 promoter, an shRNA
cassette, a reporter-free backbone, an empty vector someone is about to clone
into -- and the properties that make a plasmid hard to propagate, hard to
synthesise and hard to assemble do not care whether BT5 wrote any of it. Repeats
delete, palindromes extrude, and both do so in sequence the user brought.

So this is the door for "here is a plasmid, tell me what is wrong with it". It
shares the finding functions with the design path rather than reimplementing
them, because a survey that drifted from the design path would be wrong in
exactly the cases hardest to notice.

Two things it deliberately does NOT do. It does not designate an insertion site
-- it reports what a site scan found, including finding nothing, which on a
non-coding construct is the correct answer and not a failure. And every finding
it produces is unfixable by codon choice, because there are no codons to choose:
this is the `HARD_CHECK` class of the contract, real and reportable and not the
solver's problem. Saying so is the point rather than a limitation.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from textwrap import wrap

from bt5.core.types import Construct, Interval, Segment, SegmentKind
from bt5.vector.annotate import COMMENT_WIDTH, ORIGIN_QUALIFIER

#: Feature keys whose label marks a region as an accepted long repeat, mirroring
#: the design path so a survey and a design of the same vector agree about what
#: is a finding and what is a design feature.
from bt5.vector.backbone import DEFAULT_EXEMPT_KINDS, DEFAULT_EXEMPT_LABELS, VectorBackbone
from bt5.vector.candidates import SiteCandidate, suggest_insertion_sites
from bt5.vector.findings import (
    MAX_LOOP_BP,
    MIN_REPEAT_BP,
    MIN_STEM_BP,
    hairpin_liabilities,
    identical_exempt_repeats,
    repeat_liabilities,
)
from bt5.vector.notes import DesignNote

_DISCLAIMER = "BT5 reports what is present, never a predicted expression level, titer or yield."


@dataclass(frozen=True)
class Survey:
    """What BT5 can say about a plasmid it did not design."""

    construct: Construct
    source_name: str
    notes: tuple[DesignNote, ...] = ()
    #: Ranked openings a design COULD use. Empty is a real answer, not a failure.
    candidates: tuple[SiteCandidate, ...] = ()
    exempt: tuple[Segment, ...] = field(default_factory=tuple)

    @property
    def clean(self) -> bool:
        return not self.notes

    @property
    def has_confident_site(self) -> bool:
        return any(c.confident for c in self.candidates)

    def observed_lines(self) -> tuple[str, ...]:
        lines = [
            f"vector: {self.source_name}, {self.construct.length} bp, "
            f"{self.construct.topology.value}",
            f"features read: {len(self.construct.features)}",
        ]
        # Always stated, both ways round. Which long repeats are accepted depends
        # entirely on what the depositor annotated -- one AAV transfer plasmid in
        # hand annotates its ITRs and another does not -- so a reader looking at
        # a palindrome finding needs to know whether anything was exempted at all
        # before deciding whether they are looking at a bug or at their own ITR.
        if self.exempt:
            kept = ", ".join(sorted({s.label or s.kind.value for s in self.exempt}))
            lines.append(f"accepted long repeats, excluded from the findings: {kept}")
        else:
            lines.append(
                "no region is annotated as an ITR, LTR or repeat_region, so any "
                "long repeat below is reported as a finding"
            )
        lines.append(self._site_line())
        return tuple(lines)

    def _site_line(self) -> str:
        if not self.candidates:
            return "no open reading frame found: there is nothing here to back-translate"
        best = self.candidates[0]
        where = f"{best.interval.start + 1}..{best.interval.end}"
        if best.confident:
            return f"best coding opening: {where} (score {best.score})"
        return (
            f"no confident coding sequence: the best opening, {where}, scored "
            f"{best.score} and is more likely a marker or a fragment than the "
            f"gene of interest"
        )

    def to_comment(self) -> str:
        """The same flat layout the design path writes, minus what was not done."""
        blocks: list[str] = [f"Surveyed by BT5. {_DISCLAIMER}"]
        blocks.append("== PROVIDED BY YOU ==")
        blocks.extend(f"- {line}" for line in self.observed_lines())
        blocks.append("== GENERATED BY BT5 ==")
        blocks.append("- nothing: no sequence was designed, this is a survey only.")
        blocks.append("== NOTED BY BT5 ==")
        if self.notes:
            blocks.extend(f"- {n.render(self.construct.length)}" for n in self.notes)
        else:
            blocks.append("- nothing further to report.")
        out: list[str] = []
        for block in blocks:
            out.extend(wrap(block, width=COMMENT_WIDTH) or [""])
        return "\n".join(out)


def construct_from_backbone(
    backbone: VectorBackbone,
    *,
    exempt_kinds: Mapping[str, SegmentKind] | None = None,
    exempt_labels: Sequence[str] = DEFAULT_EXEMPT_LABELS,
) -> Construct:
    """A `Construct` with no designable region at all.

    `editable` is empty, which is the honest statement of the situation and not
    a degenerate case to work around: every base here came from the user, so
    every finding against it is unfixable by codon choice. The rules that ask
    `is_editable` get the right answer for free.
    """
    kinds = DEFAULT_EXEMPT_KINDS if exempt_kinds is None else exempt_kinds
    return Construct(
        sequence=backbone.sequence,
        topology=backbone.topology,
        segments=_segments(backbone, kinds, exempt_labels),
        translation_units=(),
        features=backbone.features,
        annotations=dict(backbone.annotations),
    )


def survey(
    backbone: VectorBackbone,
    *,
    source_name: str | None = None,
    table_id: int = 1,
    min_repeat: int = MIN_REPEAT_BP,
    min_stem: int = MIN_STEM_BP,
    max_loop: int = MAX_LOOP_BP,
) -> Survey:
    """Report what is wrong with a plasmid, without designing anything.

    `table_id` is used only to read open reading frames for the site scan, and
    is still never defaulted silently by the caller's absence of an opinion: a
    survey that reports "no CDS here" under the wrong code would be wrong in the
    one way this project refuses to be wrong. It is stated in the report.
    """
    construct = construct_from_backbone(backbone)
    notes = (
        *backbone.notes,
        *identical_exempt_repeats(construct),
        *repeat_liabilities(construct, min_len=min_repeat),
        *hairpin_liabilities(construct, min_stem=min_stem, max_loop=max_loop),
    )
    return Survey(
        construct=construct,
        source_name=source_name or backbone.name,
        notes=notes,
        candidates=tuple(suggest_insertion_sites(backbone, table_id=table_id)),
        exempt=tuple(s for s in construct.segments if s.exempt_from_scanning),
    )


def _segments(
    backbone: VectorBackbone,
    exempt_kinds: Mapping[str, SegmentKind],
    exempt_labels: Sequence[str],
) -> tuple[Segment, ...]:
    """Type every base: BACKBONE, except regions that are accepted long repeats.

    Built by typing each base and coalescing runs, the same way the design path
    does it, so overlapping annotations cannot produce two segments claiming the
    same base -- which `Construct` would then tile twice.
    """
    n = backbone.length
    kinds: list[SegmentKind] = [SegmentKind.BACKBONE] * n
    labels: list[str] = [""] * n
    for feature in backbone.features:
        label = backbone.label_of(feature)
        kind = _exempt_kind(feature.kind, label, exempt_kinds, exempt_labels)
        if kind is None:
            continue
        for pos in range(feature.interval.start, feature.interval.end):
            kinds[pos % n] = kind
            labels[pos % n] = label

    out: list[Segment] = []
    start = 0
    for i in range(1, n + 1):
        if i == n or kinds[i] is not kinds[start] or labels[i] != labels[start]:
            out.append(Segment(Interval(start, i), kinds[start], labels[start]))
            start = i
    return tuple(out)


def _exempt_kind(
    key: str,
    label: str,
    exempt_kinds: Mapping[str, SegmentKind],
    exempt_labels: Sequence[str],
) -> SegmentKind | None:
    lowered = label.casefold()
    if any(token in lowered for token in exempt_labels):
        return SegmentKind.WHITELISTED_REPEAT
    return exempt_kinds.get(key.lower())


__all__ = [
    "ORIGIN_QUALIFIER",
    "Survey",
    "construct_from_backbone",
    "survey",
]
